version: "3.9"

volumes:
  db-store:

services:
  db:
    container_name: db
    image: postgres:15.4
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=secret
      - POSTGRES_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo

  db_test:
    container_name: db_test
    image: postgres:15.4
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=secret
      - POSTGRES_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
